[package]
name = "wars-test"
version = "0.6.0"
edition = "2021"
license = "CC0-1.0"
description = "WaRs Test"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
crate-type = ["cdylib"]
